name: Dev env

on:
  push:
    branches:
      - master
      - stable
  pull_request:
  release:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Tests
      run: |
        chmod +x ./unit-tests.sh
        LOG_DIR=./logs ./unit-tests.sh